### ISSUE TITLE
nodejs project compilation

### ISSUE THREAD

**Issue by kennethlimcp** [resin-io-projects/armv7hf-debian-qemu#2] opened 2016-03-01 04:09 UTC
Hello! Thanks for this handy Docker image. Allows me to try out building an armhf image using my Mac. :)

One issue i met is:

```
+ npm install --production

/usr/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: EAFNOSUPPORT, address family not supported
    at getLocalAddresses (/usr/lib/node_modules/npm/node_modules/npmconf/config-defs.js:320:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmconf/config-defs.js:268:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/npmconf/npmconf.js:4:18)
    at Module._compile (module.js:456:26)
```

The Dockerfile contain is similar to: https://github.com/kennethlimcp/Ghost-armhf/blob/master/ghost-build/Dockerfile

Wondering if you guys managed to use it to build a `nodejs` project besides the python example? Thanks!

**Comment by petrosagg** [comment] 2016-03-01 08:17
Hey @kennethlimcp! To do this you need an extra patch to qemu which you can see here https://github.com/resin-io/qemu/commit/313be808b8b070aa1db89bdc81b39edcf8153893. Unfortunately I don't have a prebuilt binary/image to give you but it's easily fixable.

If you cherry pick that commit on top of this branch https://github.com/resin-io/qemu/commits/qemu-execve and compile a statically linked QEMU you'll be able to run nodejs just fine.

Otherwise I'll try to update the QEMU branches and release a binary on github with the fix

**Comment by kennethlimcp** [comment] 2016-03-01 11:51
@petrosagg thanks for the quick response! The cherry-picking worked fine with just a minor conflict but my Mac environment is not fulfilling the compiler requirements. Will drop a note when i get to it :)

**Comment by petrosagg** [comment] 2016-03-04 10:32
@kennethlimcp You can now use a pre-built binary :) https://github.com/resin-io/qemu/releases/tag/2.5.0-resin-rc3

**Comment by kennethlimcp** [comment] 2016-03-04 12:17
Thanks! I'll give it a shot tonight.

Did you use a Docker container to build the binary?

**Comment by petrosagg** [comment] 2016-03-04 12:26
Yeah, I committed it here https://github.com/resin-io/qemu/blob/v2.5.0-resin-rc3/Dockerfile , but now that I see it the 2 RUN commands should be run in `/usr/src/qemu`.

**Comment by kennethlimcp** [comment] 2016-03-05 14:43
@petrosagg sadly after replacing the `qemu-arm-static` binary for https://github.com/resin-io-projects/armv7hf-debian-qemu and building with: `docker build --tag resin/armv7hf-debian-qemu:latest .`

i get this when i use the image:

```
Sending build context to Docker daemon 7.558 MB
Step 1 : FROM resin/armv7hf-debian-qemu
 ---> 2553205ac3ad
Step 2 : RUN cross-build-start
 ---> Running in 75b6049e134f
Segmentation fault
/usr/bin/cross-build-start: 4: /usr/bin/cross-build-start: Cannot fork
Segmentation fault
```

Seems like we need:
- `git clone https://github.com/resin-io/qemu`
- `git checkout v2.5.0-resin-rc3`
- `git submodule update --init pixman` or install in container with `apt-get install -y libpixman-1-dev`

Dockerfile:

```
# Use this dockerfile to build the qemu binary

FROM debian:jessie

RUN apt-get update \
    && apt-get install -y \
#libtool \
        autoconf \
        build-essential \
        libglib2.0-dev \
        make \
        pkg-config \
        python \
        zlib1g-dev \
  libtool

COPY . /usr/src/qemu

WORKDIR /usr/src/qemu

RUN apt-get install -y 
RUN ./configure --target-list=arm-linux-user --static

RUN make -j $(nproc)

```

**Comment by petrosagg** [comment] 2016-03-06 01:26
I looked a bit into the issue and the problem is that rc3 uses `getauxval()` to get the path of QEMU. https://github.com/resin-io/qemu/blob/v2.5.0-resin-rc3/linux-user/main.c#L3913-L3923

In previous versions this was hardcoded. This means that my trick of setting qemu-arm-static as the interpreter for `cross-build-start`, `cross-build-end`, and `sh-shim` doesn't work. I'll fix later today, these 3 scripts have to be converted to their binary equivalent and then it will start working again.

In the meantime, I'm [attaching a QEMU binary](https://github.com/resin-io-projects/armv7hf-debian-qemu/files/160117/qemu-hardcoded.zip) that has the NF_NETLINK patch and also has the QEMU path hardcoded to `/usr/bin/qemu-arm-static`.

Regarding the qemu building Dockerfile, I don't install pixman, I think it's only needed for full system emulation.

**Comment by kennethlimcp** [comment] 2016-03-06 02:03
Thanks for checking in. :) I am unable to build with the original Dockerfile from `v2.5.0-resin-rc3` so i had to install `libtool` and get pixman in order for it to work.

Seems to be working fine now. Waiting for my armhf image of Ghost to be built. Thanks!

**Comment by jgato** [comment] 2016-09-05 07:10
Hello,

I am coming from this other [issue](https://github.com/resin-os/resin-qemu/issues/16#issuecomment-244361520), where I couldnt build images in nodejs projects.  @petrosagg  created a new version of the base arm image and now something wrong is happening.

As soon as I start building my image it goes to the step 2:

```
Step 2 : RUN cross-build-start
 ---> Running in 71e51b8881ec
```

And this process starts to create lots of cross-build-start processes and eating all the  memory of my poor laptop in very few seconds:

![docker](https://cloud.githubusercontent.com/assets/3435696/18239879/821654f6-7348-11e6-85b7-6a1bfb04e08d.png)

This makes my computer useless in just a seconds ;)

**Comment by petrosagg** [comment] 2016-09-05 09:45
Ouch. I'll check it out now

**Comment by petrosagg** [comment] 2016-09-05 12:05
@jgato I fixed the issue. Can you verify that it works for you now?

**Closed as completed** 2016-09-05 12:04 UTC

**Comment by jgato** [comment] 2016-09-05 14:03
It worked perfectly, many thanks.

**Comment by ibrahima** [comment] 2016-09-08 20:37
Huh, I'm now experiencing the issue @jgato posted about a few days ago, and my image is up to date. If I try to run, for example, 

`docker run -it -m 300M --cpu-quota 25000 resin/armv7hf-debian-qemu bash`

My computer will be locked up. I run it with CPU and memory quotas to avoid locking up my computer like so:

`docker run -it -m 300M --cpu-quota 25000 resin/armv7hf-debian-qemu bash`

But I still can't actually start bash. The strange thing is, the image from 6 months ago used to work fine, and I still have an image on my machine based on that image and that one works fine for me, but if I try to base any new Docker images on the updated base image, I get this issue. Any ideas as to what's going on?

**Comment by plegal** [comment] 2016-09-22 06:49
Your exec (https://github.com/resin-io-projects/armv7hf-debian-qemu/files/160117/qemu-hardcoded.zip) solve a part of my problem : install bower with npm under qemu-arm-static.
Now I can run bower but it hangs when I try to install package (sort of freeze of git...)
Any idea ?
Thank

**Comment by petrosagg** [comment] 2016-09-22 06:54
@plegal Yes, this is a common problem which has to do with a buggy implementation of threads in QEMU. If you strace the hung process it will most probably be blocking in a `futex()` call. I've found that running the build on a single core `docker build --cpuset-cpus=0 .` solves the issue

**Comment by plegal** [comment] 2016-09-22 07:12
Thank for your fast answer. So the problem is QEMU. I don't use docker (perhaps i should...). I've my own script that build a raspberry image under qemu-arm-static/chroot.
Is there a way to rebuild your qemu (https://github.com/resin-io-projects/armv7hf-debian-qemu/files/160117/qemu-hardcoded.zip) and configure it the right way with cpu=0?
Thanks.

**Comment by petrosagg** [comment] 2016-09-22 07:15
If you're running outside of docker I think something like `taskset`[1]  will do the job.

[1] https://linux.die.net/man/1/taskset

**Comment by plegal** [comment] 2016-09-22 08:41
Many thanks, taskset 0x00000001 ./manage.py bower install does the job (I use django) !
Last question if it's not a problem for you to answer. I use your qemu exec but what branch of https://github.com/resin-io-projects/ is used to build your qemu that solved the EAFNOSUPPORT problem ? I tried the master but this problem is still there...

**Comment by petrosagg** [comment] 2016-09-22 09:04
Happy to help :)

It's built from this branch[1] and the commit that fixes EAFNOSUPPORT is  https://github.com/resin-io/qemu/commit/313be808b8b070aa1db89bdc81b39edcf8153893

[1]  https://github.com/resin-io/qemu/tree/resin-release
